### ISSUE TITLE
.vscode

### ISSUE THREAD

**Issue by theholograms** [mauro-codes/sapper-tailwindcss-boilerplate#1]
hey, might want to .gitignore your .vscode folder. was very confused for a minute when my whole theme changed.

**Comment by mauro-codes** [comment]
omg! Sorry, my bad. I already removed it.

Thanks!

**Comment by QuantumInformation** [comment]
@mauro-codes didnt want to start a new thread

Nice work btw, I was surprised that you imported it into server.js instead of client.js.
Is there any advantage?

**Comment by QuantumInformation** [comment]
this is in server.js
`import "./main.css";`
vs client.js (which is where I thought it would have gone)

**Comment by mauro-codes** [comment]
Hi again! I just looked at server.js and there is no ìmport "./main.css"`.
